CREATE TABLE tipos(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(32) NOT NULL
); CREATE TABLE productos(
    id INT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(64) NOT NULL,
    precio FLOAT NOT NULL,
    stock INT NOT NULL,
    descripcion VARCHAR(100),
    sku VARCHAR(32) NOT NULL,
    url_image VARCHAR(64) NOT NULL,
    id_tipo INT NOT NULL,
    cliente_nombre VARCHAR(64),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(id_tipo) REFERENCES tipos(id)
); CREATE TABLE usuarios(
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL UNIQUE,
    admin BOOLEAN DEFAULT FALSE,
    password VARCHAR(64) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); CREATE TABLE carritos(
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_producto INT NOT NULL,
    id_usuario INT NOT NULL,
    cantidad INT NOT NULL,
    total FLOAT NOT NULL,
    FOREIGN KEY(id_usuario) REFERENCES usuarios(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); CREATE TABLE ventas(
    id INT PRIMARY KEY AUTO_INCREMENT,
    id_carrito INT NOT NULL,
    estado VARCHAR(32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)